#! /bin/bash

PROGNAME="$(basename "$0")"

if [ "$PROGNAME" = "howto_stub" ] ; then
    if [ -z "$1" ] ; then
	echo 1>&2 "Usage: howto_sub progname"
	exit 1
    fi
    TARGETDIR="$(dirname "$0")"
    if [ -e "$TARGETDIR/$1" ] ; then
	echo 1>&2 "$TARGETDIR/$1 already exists"
	exit 1
    fi
    set -x
    cp --archive "$0" "$TARGETDIR/$1"
else
    if [ -s "$HOWTO_TMP" ] ; then
	: nothing
    elif [ -e ~/tmp ] ; then
	HOWTO_TMP=$HOME/tmp
    else
	HOWTO_TMP=/tmp
    fi
    exec howto -T ${HOWTO_TMP} -q $PROGNAME "$@"
fi

